# This file is an override to the default 'docker-compose.yml' file, and is
# intended to be used in CI contexts (drone, github actions, semaphore, etc).
#
# The most important thing it does is re-uses the services defined in the main
# file (docker-compose.yml) such as postgres, redis, goaws, etc.
#
# To make it work, be sure you use an alias for docker-compose called
# `ci-compose`. You can create one like this:
# `alias ci-compose="docker-compose --file docker-compose.yml --file ci-compose.yml"`
version: "3.7"

services:
  test:
    image: docker.pkg.github.com/${GITHUB_REPOSITORY}/gifts-challenge:testing-${GIT_COMMIT_SHORT_SHA}
    build: &app_build
      context: .
      dockerfile: Dockerfile
      target: testing
      args: &app_build_args
        APP_PATH: ${PWD:-/srv/gifts-challenge}
        DEVELOPER_UID: ${UID:-1000} # Keep in mind, most CI/CD environments will have this variable unset!
        DEVELOPER_USERNAME: ${USER:-you}
      cache_from:
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/gifts-challenge:testing-${GIT_COMMIT_SHORT_SHA}
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/gifts-challenge:testing-${TAG_SAFE_BRANCH}
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/gifts-challenge:testing
    volumes:
      - .:${PWD:-/srv/gifts-challenge}:delegated # Mounts the app code
    entrypoint: ${PWD:-/srv/gifts-challenge}/bin/dev-entrypoint
    working_dir: ${PWD:-/srv/gifts-challenge}
    command: rspec
    depends_on:
      - postgres
      - elasticsearch
    environment:
      CI: "true"

      RAILS_ENV: test

      DATABASE_HOST_URL: ${DATABASE_URL:-SOME_DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-SOME_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-SOME_DATABASE_PASSWORD}

  release:
    image: docker.pkg.github.com/${GITHUB_REPOSITORY}/gifts-challenge:${GIT_COMMIT_SHORT_SHA}
    build:
      <<: *app_build
      target: release
      args:
        <<: *app_build_args
        SOURCE_BRANCH: ${GIT_BRANCH}
        SOURCE_COMMIT: ${GIT_COMMIT_SHA}
        BUILD_DATE: ${BUILD_DATE}
        IMAGE_NAME: "ivan/gifts-challenge"
